services:
    upro.form_type.u_pro_file:
        class: UPro\FileBundle\Form\UProFileType
        arguments: [ @file.om, %u_pro_file.db_driver% ]
        tags:
            - { name: form.type, alias: u_pro_file }